DROP DATABASE IF EXISTS MIGRATE;

CREATE DATABASE MIGRATE;

USE MIGRATE;

CREATE TABLE users (
ID int NOT NULL AUTO_INCREMENT,
userid VARCHAR(255),
token VARCHAR (255),
username VARCHAR(255),
email VARCHAR(255),
PRIMARY KEY (ID)
);